// Downloads the app's fonts once (latin subset, woff2) into docs/fonts and
// writes docs/css/fonts.css. Run with: npm run fonts
// The app itself never loads fonts from the network at runtime.
import { writeFile, mkdir } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const fontDir = path.join(root, 'docs', 'fonts');
const cssFile = path.join(root, 'docs', 'css', 'fonts.css');

const FAMILIES = [
  { family: 'Cormorant Garamond', query: 'Cormorant+Garamond:wght@600;700', ofl: 'cormorantgaramond', slug: 'cormorant-garamond' },
  { family: 'EB Garamond', query: 'EB+Garamond:wght@400;500', ofl: 'ebgaramond', slug: 'eb-garamond' },
  { family: 'Jost', query: 'Jost:wght@500', ofl: 'jost', slug: 'jost' },
];

// An older browser signature makes Google Fonts serve one static file per
// weight instead of a variable font, so every engine renders the exact
// weights of the brief (600 and 700, 400 and 500) without relying on
// variable-font support.
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36';

async function get(url, as = 'text') {
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`${res.status} ${url}`);
  return as === 'buffer' ? Buffer.from(await res.arrayBuffer()) : res.text();
}

await mkdir(fontDir, { recursive: true });
const faces = [];
const files = new Map(); // url -> local file name
const licences = [];

for (const f of FAMILIES) {
  const css = await get(`https://fonts.googleapis.com/css2?family=${f.query}&display=swap`);
  // Each block is preceded by a subset comment such as /* latin */
  const blocks = [...css.matchAll(/\/\*\s*([\w-]+)\s*\*\/\s*@font-face\s*{([^}]*)}/g)];
  for (const [, subset, body] of blocks) {
    if (subset !== 'latin') continue;
    const weight = body.match(/font-weight:\s*(\d+)/)[1];
    const style = body.match(/font-style:\s*(\w+)/)[1];
    const url = body.match(/url\(([^)]+)\)/)[1];
    const range = body.match(/unicode-range:\s*([^;]+);/)[1].trim();
    if (!files.has(url)) {
      const buf = await get(url, 'buffer');
      const hash = createHash('sha256').update(buf).digest('hex').slice(0, 8);
      const name = `${f.slug}-${weight}-${hash}.woff2`;
      await writeFile(path.join(fontDir, name), buf);
      files.set(url, name);
      console.log(`saved ${name} (${buf.length} bytes)`);
    }
    // Google serves one variable file for several weights: merge them into one rule.
    const same = faces.find((x) => x.file === files.get(url) && x.style === style);
    if (same) same.weights.push(Number(weight));
    else faces.push({ family: f.family, weights: [Number(weight)], style, file: files.get(url), range });
  }
  const ofl = await get(`https://raw.githubusercontent.com/google/fonts/main/ofl/${f.ofl}/OFL.txt`);
  licences.push(`${f.family}\n${'='.repeat(f.family.length)}\n\n${ofl.trim()}\n`);
}

const out = faces.map((x) => {
  const lo = Math.min(...x.weights);
  const hi = Math.max(...x.weights);
  return `@font-face {
  font-family: '${x.family}';
  font-style: ${x.style};
  font-weight: ${lo === hi ? lo : `${lo} ${hi}`};
  font-display: swap;
  src: url('../fonts/${x.file}') format('woff2');
  unicode-range: ${x.range};
}`;
}).join('\n\n');

await writeFile(cssFile, `/* Generated by tools/fetch-fonts.mjs. Fonts are licensed under the SIL Open Font License (see fonts/OFL.txt). */\n\n${out}\n`);
await writeFile(path.join(fontDir, 'OFL.txt'), licences.join('\n\n'));
console.log(`wrote ${faces.length} @font-face rules to docs/css/fonts.css`);
